POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Dummy",
    "number": "09-1234556"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "d",
    "number": "09-1234556"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Dummy",
    "number": ""
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Arto Hellas",
    "number": "0900123123"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Dummy1",
    "number": "19-11111"
}
